#==============================================================
#
#  Abs: Generate Archive list  
#
#  Facility: GunB LLRF
#
#  Auth: 13-Feb-2019, Garth Brown  (gwbrown)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#
#============================================================== 
#
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#

ARCHIVE += $(IOCADMIN)/iocAdmin/Db/archive_iocAdmin.tpl-arch

ARCHIVE += BMB7monitor.archive
ARCHIVE += sioc-gunb-rf01.archive
ARCHIVE += sioc-gunb-rf02.archive
ARCHIVE += BuncherRfCalib.archive
ARCHIVE += GunRfCalib.archive


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


