d = { "name" : "scllrfINT",
    'registers': [
 {
   "name": "R1CWAV",
   "address": 0,
   "Hex": "0",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity1 arc detector voltage readback",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R2CWAV",
   "address": 1,
   "Hex": "1",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity2 arc detector voltage readback",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R3CWAV",
   "address": 2,
   "Hex": "2",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity3 arc detector voltage readback",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R4CWAV",
   "address": 3,
   "Hex": "3",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity4 arc detector voltage readback",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R1CWAPS",
   "address": 4,
   "Hex": "4",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 1 arc detector power supply set voltage",
   "ASLO": 0.0001296997
 },
 {
   "name": "R2CWAPS",
   "address": 5,
   "Hex": "5",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 2 arc detector power supply set voltage",
   "ASLO": 0.0001296997
 },
 {
   "name": "R3CWAPS",
   "address": 6,
   "Hex": "6",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 3 arc detector power supply set voltage",
   "ASLO": 0.0001296997
 },
 {
   "name": "R4CWAPS",
   "address": 7,
   "Hex": "7",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 4 arc detector power supply set voltage",
   "ASLO": 0.0001296997
 },
 {
   "name": "R1CWAL",
   "address": 8,
   "Hex": "8",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 1 arc detector limit volts",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R2CWAL",
   "address": 9,
   "Hex": "9",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 2 arc detector limit volts",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R3CWAL",
   "address": 10,
   "Hex": "A",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 3 arc detector limit volts",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R4CWAL",
   "address": 11,
   "Hex": "B",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 4 arc detector limit volts",
   "ASLO": 0.0000019073486328125
 },
 {
   "name": "R1CWAP",
   "address": 12,
   "Hex": "C",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 1 arc detector period usec",
   "ASLO": 0.02
 },
 {
   "name": "R2CWAP",
   "address": 13,
   "Hex": "D",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 2 arc detector period usec",
   "ASLO": 0.02
 },
 {
   "name": "R3CWAP",
   "address": 14,
   "Hex": "E",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 3 arc detector period usec",
   "ASLO": 0.02
 },
 {
   "name": "R4CWAP",
   "address": 15,
   "Hex": "F",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 4 arc detector period usec",
   "ASLO": 0.02
 },
 {
   "name": "RXCWAD",
   "address": 16,
   "Hex": "10",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "arc faults latched and instantaneous",
 },
 {
   "name": "RXCWAM",
   "address": 17,
   "Hex": "11",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "arc fault mask",
 },
 {
   "name": "RXCWAT",
   "address": 18,
   "Hex": "12",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "arc detector led test",
 },
 {
   "name": "RXATFLT",
   "address": 19,
   "Hex": "13",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "arc detector led test fault status",
 },
 {
   "name": "RXCWAFC",
   "address": 20,
   "Hex": "14",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "arc fault clear",
 },
 {
   "name": "R1CWWT",
   "address": 21,
   "Hex": "15",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 window voltage readback",
   "ASLO": 0.0000015625
 },
 {
   "name": "R2CWWT",
   "address": 22,
   "Hex": "16",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 window voltage readback",
   "ASLO": 0.0000015625
 },
 {
   "name": "R3CWWT",
   "address": 23,
   "Hex": "17",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 window voltage readback",
   "ASLO": 0.0000015625
 },
 {
   "name": "R4CWWT",
   "address": 24,
   "Hex": "18",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 window voltage readback",
   "ASLO": 0.0000015625
 },
 {
   "name": "R1CWWL",
   "address": 25,
   "Hex": "19",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 window limit volts",
   "ASLO": 0.0000015625
 },
 {
   "name": "R2CWWL",
   "address": 26,
   "Hex": "1A",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 window limit volts",
   "ASLO": 0.0000015625
 },
 {
   "name": "R3CWWL",
   "address": 27,
   "Hex": "1B",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 window limit volts",
   "ASLO": 0.0000015625
 },
 {
   "name": "R4CWWL",
   "address": 28,
   "Hex": "1C",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 window limit volts",
   "ASLO": 0.0000015625
 },
 {
   "name": "RXCWWD",
   "address": 29,
   "Hex": "1D",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "window faults latched and instantaneous",
 },
 {
   "name": "RXCWWTS",
   "address": 30,
   "Hex": "1E",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "window ir sensor test",
 },
 {
   "name": "RXCWWM",
   "address": 31,
   "Hex": "1F",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "window fault mask",
 },
 {
   "name": "RXCWWFC",
   "address": 32,
   "Hex": "20",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "window fault clear",
 },
 {
   "name": "R1STMPI",
   "address": 33,
   "Hex": "21",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 1 stepper motor PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R2STMPI",
   "address": 34,
   "Hex": "22",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 2 stepper motor PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R3STMPI",
   "address": 35,
   "Hex": "23",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 3 stepper motor PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R4STMPI",
   "address": 36,
   "Hex": "24",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 4 stepper motor PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R1STMPV",
   "address": 37,
   "Hex": "25",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 stepper motor PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R2STMPV",
   "address": 38,
   "Hex": "26",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 stepper motor PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R3STMPV",
   "address": 39,
   "Hex": "27",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 stepper motor PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R4STMPV",
   "address": 40,
   "Hex": "28",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 stepper motor PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R1STMPVL",
   "address": 41,
   "Hex": "29",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 stepper motor PT100 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R2STMPVL",
   "address": 42,
   "Hex": "2A",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 stepper motor PT100 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R3STMPVL",
   "address": 43,
   "Hex": "2B",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 stepper motor PT100 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R4STMPVL",
   "address": 44,
   "Hex": "2C",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 stepper motor PT100 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "RXSTMPLS",
   "address": 45,
   "Hex": "2D",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "stepper motor temperature limit status",
 },
 {
   "name": "RXSTMPM",
   "address": 46,
   "Hex": "2E",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "stepper motor temperature limit mask",
 },
 {
   "name": "RXSTMPFC",
   "address": 47,
   "Hex": "2F",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "stepper motor temperature limit fault clear",
 },
 {
   "name": "R1CPLTMP1I",
   "address": 48,
   "Hex": "30",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 1 coupler PT100 1 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R1CPLTMP2I",
   "address": 49,
   "Hex": "31",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 1 coupler PT100 2 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R2CPLTMP1I",
   "address": 50,
   "Hex": "32",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 2 coupler PT100 1 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R2CPLTMP2I",
   "address": 51,
   "Hex": "33",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 2 coupler PT100 2 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R3CPLTMP1I",
   "address": 52,
   "Hex": "34",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 3 coupler PT100 1 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R3CPLTMP2I",
   "address": 53,
   "Hex": "35",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 3 coupler PT100 2 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R4CPLTMP1I",
   "address": 54,
   "Hex": "36",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 4 coupler PT100 1 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R4CPLTMP2I",
   "address": 55,
   "Hex": "37",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "cavity 4 coupler PT100 2 excitation current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R1CPLTMP1V",
   "address": 56,
   "Hex": "38",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 coupler PT100 1 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R1CPLTMP2V",
   "address": 57,
   "Hex": "39",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 coupler PT100 2 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R2CPLTMP1V",
   "address": 58,
   "Hex": "3A",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 coupler PT100 1 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R2CPLTMP2V",
   "address": 59,
   "Hex": "3B",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 coupler PT100 2 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R3CPLTMP1V",
   "address": 60,
   "Hex": "3C",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 coupler PT100 1 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R3CPLTMP2V",
   "address": 61,
   "Hex": "3D",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 coupler PT100 2 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R4CPLTMP1V",
   "address": 62,
   "Hex": "3E",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 coupler PT100 1 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R4CPLTMP2V",
   "address": 63,
   "Hex": "3F",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 coupler PT100 2 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R1CPLTMP1VL",
   "address": 64,
   "Hex": "40",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 coupler PT100 1 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R1CPLTMP2VL",
   "address": 65,
   "Hex": "41",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 1 coupler PT100 2 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R2CPLTMP1VL",
   "address": 66,
   "Hex": "42",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 coupler PT100 1 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R2CPLTMP2VL",
   "address": 67,
   "Hex": "43",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 2 coupler PT100 2 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R3CPLTMP1VL",
   "address": 68,
   "Hex": "44",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 coupler PT100 1 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R3CPLTMP2VL",
   "address": 69,
   "Hex": "45",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 3 coupler PT100 2 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R4CPLTMP1VL",
   "address": 70,
   "Hex": "46",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 coupler PT100 1 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "R4CPLTMP2VL",
   "address": 71,
   "Hex": "47",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "cavity 4 coupler PT100 2 voltage limit",
   "ASLO": 5.3e-8
 },
 {
   "name": "RXCPLTMPLS",
   "address": 72,
   "Hex": "48",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler temperature limit status",
 },
 {
   "name": "RXCPLTMPM",
   "address": 73,
   "Hex": "49",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler temperature limit mask status",
 },
 {
   "name": "RXCPLTMPFC",
   "address": 74,
   "Hex": "4A",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler temperature limit fault clear",
 },
 {
   "name": "R1CPLFEP1I",
   "address": 75,
   "Hex": "4B",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 1 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP2I",
   "address": 76,
   "Hex": "4C",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 2 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP3I",
   "address": 77,
   "Hex": "4D",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 3 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP1I",
   "address": 78,
   "Hex": "4E",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 1 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP2I",
   "address": 79,
   "Hex": "4F",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 2 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP3I",
   "address": 80,
   "Hex": "50",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 3 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP1I",
   "address": 81,
   "Hex": "51",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 1 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP2I",
   "address": 82,
   "Hex": "52",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 2 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP3I",
   "address": 83,
   "Hex": "53",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 3 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP1I",
   "address": 84,
   "Hex": "54",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 1 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP2I",
   "address": 85,
   "Hex": "55",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 2 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP3I",
   "address": 86,
   "Hex": "56",
   "access": "r",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 3 current readback uA",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP1ILH",
   "address": 87,
   "Hex": "57",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 1 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP2ILH",
   "address": 88,
   "Hex": "58",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 2 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP3ILH",
   "address": 89,
   "Hex": "59",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 3 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP1ILH",
   "address": 90,
   "Hex": "5A",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 1 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP2ILH",
   "address": 91,
   "Hex": "5B",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 2 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP3ILH",
   "address": 92,
   "Hex": "5C",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 3 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP1ILH",
   "address": 93,
   "Hex": "5D",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 1 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP2ILH",
   "address": 94,
   "Hex": "5E",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 2 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP3ILH",
   "address": 95,
   "Hex": "5F",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 3 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP1ILH",
   "address": 96,
   "Hex": "60",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 1 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP2ILH",
   "address": 97,
   "Hex": "61",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 2 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP3ILH",
   "address": 98,
   "Hex": "62",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 3 current limit high",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP1ILL",
   "address": 99,
   "Hex": "63",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 1 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP2ILL",
   "address": 100,
   "Hex": "64",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 2 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R1CPLFEP3ILL",
   "address": 101,
   "Hex": "65",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 1 electron probe 3 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP1ILL",
   "address": 102,
   "Hex": "66",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 1 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP2ILL",
   "address": 103,
   "Hex": "67",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 2 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R2CPLFEP3ILL",
   "address": 104,
   "Hex": "68",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 2 electron probe 3 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP1ILL",
   "address": 105,
   "Hex": "69",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 1 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP2ILL",
   "address": 106,
   "Hex": "6A",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 2 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R3CPLFEP3ILL",
   "address": 107,
   "Hex": "6B",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 3 electron probe 3 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP1ILL",
   "address": 108,
   "Hex": "6C",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 1 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP2ILL",
   "address": 109,
   "Hex": "6D",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 2 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "R4CPLFEP3ILL",
   "address": 110,
   "Hex": "6E",
   "access": "rw",
   "signed": "signed",
   "bits": "",
   "desc": "coupler 4 electron probe 3 current limit low",
   "ASLO": 0.6103515625
 },
 {
   "name": "RXCPLFEPM",
   "address": 111,
   "Hex": "6F",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler electron probe limit mask",
 },
 {
   "name": "RXCPLFEPLS",
   "address": 112,
   "Hex": "70",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler electron probe limit status",
 },
 {
   "name": "RXCPLFEPFS",
   "address": 113,
   "Hex": "71",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler electron probe limit latched status",
 },
 {
   "name": "RXCPLFEPFC",
   "address": 114,
   "Hex": "72",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "coupler electro probe fault clear",
 },
 {
   "name": "RXCVF",
   "address": 115,
   "Hex": "73",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "vacuum fault status",
 },
 {
   "name": "RXCVFM",
   "address": 116,
   "Hex": "74",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "vacuum fault mask",
 },
 {
   "name": "RXCVFC",
   "address": 117,
   "Hex": "75",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "vacuum fault clear",
 },
 {
   "name": "RXCIEN",
   "address": 118,
   "Hex": "76",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "interlock enable latch and present from FCC",
 },
 {
   "name": "RXCIENM",
   "address": 119,
   "Hex": "77",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "interlock enable latch and present from FCC mask",
 },
 {
   "name": "RXCIENC",
   "address": 120,
   "Hex": "78",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "interlock enable clear",
 },
 {
   "name": "RXFFSD",
   "address": 121,
   "Hex": "79",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "FSD to field control latch and present",
 },
 {
   "name": "RXFFSDM",
   "address": 122,
   "Hex": "7A",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "FSD to field control latch and present mask",
 },
 {
   "name": "RXFFSDC",
   "address": 123,
   "Hex": "7B",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "FSD to field control clear",
 },
 {
   "name": "RXISTAT",
   "address": 124,
   "Hex": "7C",
   "access": "r",
   "signed": "unsigned",
   "bits": {},
   "desc": "miscellaneous status bits",
 },
 {
   "name": "RXICTL",
   "address": 125,
   "Hex": "7D",
   "access": "rw",
   "signed": "unsigned",
   "bits": {},
   "desc": "miscellaneous control bits",
 },
 {
   "name": "RXIVER",
   "address": 126,
   "Hex": "7E",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "firmware version",
 },
 {
   "name": "R1CPLFEP1PERD",
   "address": 127,
   "Hex": "7F",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 1 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R1CPLFEP2PERD",
   "address": 128,
   "Hex": "80",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 2 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R1CPLFEP3PERD",
   "address": 129,
   "Hex": "81",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 3 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R2CPLFEP1PERD",
   "address": 130,
   "Hex": "82",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 4 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R2CPLFEP2PERD",
   "address": 131,
   "Hex": "83",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 5 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R2CPLFEP3PERD",
   "address": 132,
   "Hex": "84",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 6 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R3CPLFEP1PERD",
   "address": 133,
   "Hex": "85",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 7 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R3CPLFEP2PERD",
   "address": 134,
   "Hex": "86",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 8 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R3CPLFEP3PERD",
   "address": 135,
   "Hex": "87",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 9 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R4CPLFEP1PERD",
   "address": 136,
   "Hex": "88",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 10 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R4CPLFEP2PERD",
   "address": 137,
   "Hex": "89",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 11 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R4CPLFEP3PERD",
   "address": 138,
   "Hex": "8A",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Coupler 12 field emission detection window period in us",
   "ASLO": 0.02
 },
 {
   "name": "R5STMPI",
   "address": 139,
   "Hex": "8B",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 1 PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R6STMPI",
   "address": 140,
   "Hex": "8C",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 2 PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R7STMPI",
   "address": 141,
   "Hex": "8D",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 3 PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R8STMPI",
   "address": 142,
   "Hex": "8E",
   "access": "rw",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 4 PT100 excitaion current mA",
   "ASLO": 0.0000762939453125
 },
 {
   "name": "R5STMPV",
   "address": 143,
   "Hex": "8F",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "spare 1 PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R6STMPV",
   "address": 144,
   "Hex": "90",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 2 PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R7STMPV",
   "address": 145,
   "Hex": "91",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 3 PT100 voltage readback",
   "ASLO": 5.3e-8
 },
 {
   "name": "R8STMPV",
   "address": 146,
   "Hex": "92",
   "access": "r",
   "signed": "unsigned",
   "bits": "",
   "desc": "Spare 4 PT100 voltage readback",
   "ASLO": 5.3e-8
 }
]
}

