TOP=../../..

include \$(TOP)/configure/CONFIG
\#----------------------------------------
\#----------------------------------------
\#  ADD MACRO DEFINITIONS AFTER THIS LINE
\#=============================

\#==================================================
\# Build an IOC support library

LIBRARY_IOC += ${name}

DBD += ${name}DriverSupport.dbd

\# The following are compiled and added to the Support library
${name}_SRCS += ${name}Driver.cpp

${name}_LIBS += DeviceLibrary
${name}_LIBS += cpswAsynPortDriverSupport
${name}_LIBS += asyn
${name}_LIBS += \$(EPICS_BASE_IOC_LIBS)
USR_INCLUDES += \$(CPSW_FRAMEWORK_INCLUDE)
USR_INCLUDES += \$(BOOST_INCLUDE)
include \$(TOP)/configure/RULES
\#----------------------------------------
\#  ADD RULES AFTER THIS LINE

