d = { "name" : "scllrfPRC",
	'registers': [
	{	"name" :"Hell",
		"address"     : 0,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"o_wo",
		"address"     : 1,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"rld_",
		"address"     : 2,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"d0a0d0a",
		"address"     : 3,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"llspi_status",
		"address"     : 4,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"llspi_result",
		"address"     : 5,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"clk_status_out",
		"address"     : 6,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"ffffffff",
		"address"     : 7,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"frequency_adc",
		"address"     : 8,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"frequency_4xout",
		"address"     : 9,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"frequency_clkout3",
		"address"     : 10,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"frequency_dco",
		"address"     : 11,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U2dout_Bits31to0",
		"address"     : 12,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U2dout_Bits63to32",
		"address"     : 13,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"idelay_value_out_U2_Bits19to0",
		"address"     : 14,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"idelay_value_out_U2_Bits39to20",
		"address"     : 15,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U3dout_Bits31to0",
		"address"     : 16,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U3dout_Bits63to32",
		"address"     : 17,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"idelay_value_out_U3_Bits19to0",
		"address"     : 18,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"idelay_value_out_U3_Bits39to20",
		"address"     : 19,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"wave0_out",
		"address"     : 20,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"wave1_out",
		"address"     : 21,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"adc_test_wave1_out",
		"address"     : 22,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"adc_test_wave2_out",
		"address"     : 23,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"adc_test_wave3_out",
		"address"     : 24,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"adc_test_wave4_out",
		"address"     : 25,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"ctrace_running",
		"address"     : 28,
		"bit_width"      : 14,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"frequency_gtx_tx",
		"address"     : 29,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"frequency_gtx_rx",
		"address"     : 30,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"hist_status",
		"address"     : 31,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"phasex_status",
		"address"     : 46,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"clk_phase_diff_out_U2",
		"address"     : 47,
		"bit_width"      : 13,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"clk_phase_diff_out_U3",
		"address"     : 48,
		"bit_width"      : 13,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"crc_errors",
		"address"     : 49,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"_U15_spi_rdbk",
		"address"     : 56,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_sdo_addr",
		"address"     : 56,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_spi_ready",
		"address"     : 57,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_sdio_as_sdo",
		"address"     : 57,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U18_sdo_addr",
		"address"     : 60,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"_U18_spi_rdbk",
		"address"     : 60,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U18_sdio_as_sdo",
		"address"     : 61,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U18_spi_ready",
		"address"     : 61,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"adc_test_trig_cnt",
		"address"     : 64,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"waveforms_available",
		"address"     : 65,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"banyan_status",
		"address"     : 66,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"slow_chain_out",
		"address"     : 67,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"trace_status1",
		"address"     : 68,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"trace_status2",
		"address"     : 69,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"llrf_circle_ready",
		"address"     : 70,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"idelay_base",
		"address"     : 112,
		"bit_width"      : 7,
		"nelm"      : 16,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"hist_dout",
		"address"     : 1048576,
		"bit_width"      : 16,
		"nelm"      : 65536,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"phasex_dout",
		"address"     : 1114112,
		"bit_width"      : 16,
		"nelm"      : 1024,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"banyan_buf",
		"address"     : 1179648,
		"bit_width"      : 32,
		"nelm"      : 65536,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"scanner_result",
		"address"     : 1245184,
		"bit_width"      : 8,
		"nelm"      : 2048,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"trace_iq_buf",
		"address"     : 1310720,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"trace_i_buf",
		"address"     : 1343488,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"trace_q_buf",
		"address"     : 1359872,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"qsfp_buf",
		"address"     : 1388544,
		"bit_width"      : 8,
		"nelm"      : 256,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"llrf_circle_data",
		"address"     : 1507328,
		"bit_width"      : 16,
		"nelm"      : 4096,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"shell_0_slow_data",
		"address"     : 1572864,
		"bit_width"      : 8,
		"nelm"      : 128,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"shell_1_slow_data",
		"address"     : 1638400,
		"bit_width"      : 8,
		"nelm"      : 128,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_cav4_mech_noise_couple_k_out",
		"address"     : 8388608,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_cav4_mech_resonator_prop_const",
		"address"     : 8389632,
		"bit_width"      : 21,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_elec_dot_0_k_out",
		"address"     : 8390656,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_dot_1_k_out",
		"address"     : 8391680,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_dot_2_k_out",
		"address"     : 8392704,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_outer_prod_0_k_out",
		"address"     : 8393728,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_outer_prod_1_k_out",
		"address"     : 8394752,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_outer_prod_2_k_out",
		"address"     : 8395776,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_piezo_couple_k_out",
		"address"     : 8396800,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_dot_0_k_out",
		"address"     : 8397824,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_dot_1_k_out",
		"address"     : 8398848,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_dot_2_k_out",
		"address"     : 8399872,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_outer_prod_0_k_out",
		"address"     : 8400896,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_outer_prod_1_k_out",
		"address"     : 8401920,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_outer_prod_2_k_out",
		"address"     : 8402944,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_piezo_couple_k_out",
		"address"     : 8403968,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"tgen_0_delay_pc_XXX",
		"address"     : 8404992,
		"bit_width"      : 32,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"tgen_1_delay_pc_XXX",
		"address"     : 8406016,
		"bit_width"      : 32,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_piezo_sf_consts",
		"address"     : 8407040,
		"bit_width"      : 20,
		"nelm"      : 8,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_piezo_sf_consts",
		"address"     : 8407048,
		"bit_width"      : 20,
		"nelm"      : 8,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_mp_proc_coeff",
		"address"     : 8407056,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_mp_proc_lim",
		"address"     : 8407060,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_mp_proc_setmp",
		"address"     : 8407064,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_mp_proc_coeff",
		"address"     : 8407068,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_mp_proc_lim",
		"address"     : 8407072,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_mp_proc_setmp",
		"address"     : 8407076,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_drive_cpl_out_coupling",
		"address"     : 8407080,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_drive_cpl_out_phase_offset",
		"address"     : 8407082,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m0_out_cpl_out_coupling",
		"address"     : 8407084,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m0_out_cpl_out_phase_offset",
		"address"     : 8407086,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m1_out_cpl_out_coupling",
		"address"     : 8407088,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m1_out_cpl_out_phase_offset",
		"address"     : 8407090,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m2_out_cpl_out_coupling",
		"address"     : 8407092,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m2_out_cpl_out_phase_offset",
		"address"     : 8407094,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_drive_cpl_out_coupling",
		"address"     : 8407096,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_drive_cpl_out_phase_offset",
		"address"     : 8407098,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m0_out_cpl_out_coupling",
		"address"     : 8407100,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m0_out_cpl_out_phase_offset",
		"address"     : 8407102,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m1_out_cpl_out_coupling",
		"address"     : 8407104,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m1_out_cpl_out_phase_offset",
		"address"     : 8407106,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m2_out_cpl_out_coupling",
		"address"     : 8407108,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m2_out_cpl_out_phase_offset",
		"address"     : 8407110,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_lp_notch_lp1a_kx",
		"address"     : 8407112,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_lp_notch_lp1a_ky",
		"address"     : 8407114,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_lp_notch_lp1b_kx",
		"address"     : 8407116,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_lp_notch_lp1b_ky",
		"address"     : 8407118,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_lp_notch_lp1a_kx",
		"address"     : 8407120,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_lp_notch_lp1a_ky",
		"address"     : 8407122,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_lp_notch_lp1b_kx",
		"address"     : 8407124,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_lp_notch_lp1b_ky",
		"address"     : 8407126,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"adc_mmcm",
		"address"     : 8407128,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U15_spi_data_addr_r",
		"address"     : 8407129,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U15_spi_read_and_start_r",
		"address"     : 8407130,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U18_spi_data_addr_r",
		"address"     : 8407131,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U18_spi_read_and_start_r",
		"address"     : 8407132,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U2_clk_reset_r",
		"address"     : 8407133,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U2_iserdes_reset_r",
		"address"     : 8407134,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U3_clk_reset_r",
		"address"     : 8407135,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U3_iserdes_reset_r",
		"address"     : 8407136,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_U4_reset_r",
		"address"     : 8407137,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_banyan_mask",
		"address"     : 8407138,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_bitslip",
		"address"     : 8407139,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_clk_status_we",
		"address"     : 8407140,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_idelayctrl_reset_r",
		"address"     : 8407141,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_llspi_we",
		"address"     : 8407142,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_mmcm_reset_r",
		"address"     : 8407143,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_periph_config",
		"address"     : 8407144,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_phasex_trig",
		"address"     : 8407145,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_rawadc_trig",
		"address"     : 8407146,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_scan_trigger_we",
		"address"     : 8407147,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_scanner_debug",
		"address"     : 8407148,
		"bit_width"      : 5,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_sync_ad7794_cset",
		"address"     : 8407149,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_config_sync_tps62210_cset",
		"address"     : 8407150,
		"bit_width"      : 6,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_adc_test_mode",
		"address"     : 8407151,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_adc_test_reset",
		"address"     : 8407152,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_amplitude",
		"address"     : 8407153,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_average_len",
		"address"     : 8407154,
		"bit_width"      : 30,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_buf_trig",
		"address"     : 8407155,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_cic_period",
		"address"     : 8407156,
		"bit_width"      : 14,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_cic_shift",
		"address"     : 8407157,
		"bit_width"      : 4,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_circle_buf_flip",
		"address"     : 8407158,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_dac_dds_reset",
		"address"     : 8407159,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_dac_mode",
		"address"     : 8407160,
		"bit_width"      : 4,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ddsa_modulo",
		"address"     : 8407161,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ddsa_phstep_h",
		"address"     : 8407162,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ddsa_phstep_l",
		"address"     : 8407163,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_hist_count_w_strobe",
		"address"     : 8407164,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_llrf_dsp_dac_en",
		"address"     : 8407165,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_lo_amp",
		"address"     : 8407166,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_modulo",
		"address"     : 8407167,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_phase_step_h",
		"address"     : 8407168,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_phase_step_l",
		"address"     : 8407169,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_prc_dsp_cav_sel",
		"address"     : 8407170,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_prc_dsp_prl_cfg",
		"address"     : 8407171,
		"bit_width"      : 9,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_prc_dsp_prl_gain",
		"address"     : 8407172,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_beam_0_modulo",
		"address"     : 8407173,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_beam_0_phase_init",
		"address"     : 8407174,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_beam_0_phase_step",
		"address"     : 8407175,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_beam_1_modulo",
		"address"     : 8407176,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_beam_1_phase_init",
		"address"     : 8407177,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_beam_1_phase_step",
		"address"     : 8407178,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_cav4_mech_prng_iva",
		"address"     : 8407179,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_cav4_mech_prng_ivb",
		"address"     : 8407180,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_cav4_mech_prng_random_run",
		"address"     : 8407181,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_a_cav_offset",
		"address"     : 8407182,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_a_for_offset",
		"address"     : 8407183,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_a_rfl_offset",
		"address"     : 8407184,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_amp_lp_bw",
		"address"     : 8407185,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_freq_0_coarse_freq",
		"address"     : 8407186,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_freq_1_coarse_freq",
		"address"     : 8407187,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_freq_2_coarse_freq",
		"address"     : 8407188,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m0_beam_coupling",
		"address"     : 8407189,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m0_bw",
		"address"     : 8407190,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m0_drive_coupling",
		"address"     : 8407191,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m1_beam_coupling",
		"address"     : 8407192,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m1_bw",
		"address"     : 8407193,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m1_drive_coupling",
		"address"     : 8407194,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m2_beam_coupling",
		"address"     : 8407195,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m2_bw",
		"address"     : 8407196,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_m2_drive_coupling",
		"address"     : 8407197,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c0_elec_modulo",
		"address"     : 8407198,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_elec_phase_step",
		"address"     : 8407199,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_compr_sat_ctl",
		"address"     : 8407200,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_prng_iva",
		"address"     : 8407201,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_prng_ivb",
		"address"     : 8407202,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c0_prng_random_run",
		"address"     : 8407203,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c1_a_cav_offset",
		"address"     : 8407204,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_a_for_offset",
		"address"     : 8407205,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_a_rfl_offset",
		"address"     : 8407206,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_amp_lp_bw",
		"address"     : 8407207,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_freq_0_coarse_freq",
		"address"     : 8407208,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_freq_1_coarse_freq",
		"address"     : 8407209,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_freq_2_coarse_freq",
		"address"     : 8407210,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m0_beam_coupling",
		"address"     : 8407211,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m0_bw",
		"address"     : 8407212,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m0_drive_coupling",
		"address"     : 8407213,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m1_beam_coupling",
		"address"     : 8407214,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m1_bw",
		"address"     : 8407215,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m1_drive_coupling",
		"address"     : 8407216,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m2_beam_coupling",
		"address"     : 8407217,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m2_bw",
		"address"     : 8407218,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_m2_drive_coupling",
		"address"     : 8407219,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_c1_elec_modulo",
		"address"     : 8407220,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c1_elec_phase_step",
		"address"     : 8407221,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c1_compr_sat_ctl",
		"address"     : 8407222,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c1_prng_iva",
		"address"     : 8407223,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c1_prng_ivb",
		"address"     : 8407224,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_c1_prng_random_run",
		"address"     : 8407225,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_dac_iq_phase",
		"address"     : 8407226,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_chan_keep",
		"address"     : 8407227,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_coarse_scale",
		"address"     : 8407228,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_mp_proc_ph_offset",
		"address"     : 8407229,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_mp_proc_sel_en",
		"address"     : 8407230,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_fdbk_core_mp_proc_sel_thresh",
		"address"     : 8407231,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_modulo",
		"address"     : 8407232,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_phase_step",
		"address"     : 8407233,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_piezo_piezo_dc",
		"address"     : 8407234,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_tag",
		"address"     : 8407235,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_use_fiber_iq",
		"address"     : 8407236,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_wave_samp_per",
		"address"     : 8407237,
		"bit_width"      : 7,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_0_dsp_wave_shift",
		"address"     : 8407238,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_chan_keep",
		"address"     : 8407239,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_coarse_scale",
		"address"     : 8407240,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_mp_proc_ph_offset",
		"address"     : 8407241,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_mp_proc_sel_en",
		"address"     : 8407242,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_fdbk_core_mp_proc_sel_thresh",
		"address"     : 8407243,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_modulo",
		"address"     : 8407244,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_phase_step",
		"address"     : 8407245,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_piezo_piezo_dc",
		"address"     : 8407246,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_tag",
		"address"     : 8407247,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_use_fiber_iq",
		"address"     : 8407248,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_wave_samp_per",
		"address"     : 8407249,
		"bit_width"      : 7,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mux_shell_1_dsp_wave_shift",
		"address"     : 8407250,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rewind",
		"address"     : 8407251,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_ampstep",
		"address"     : 8407252,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_en",
		"address"     : 8407253,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_g_period",
		"address"     : 8407254,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_pertstep",
		"address"     : 8407255,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trace_keep",
		"address"     : 8407256,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trace_reset_we",
		"address"     : 8407257,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trig_internal",
		"address"     : 8407258,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trig_mode",
		"address"     : 8407259,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_wave0_src",
		"address"     : 8407260,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_wave1_src",
		"address"     : 8407261,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"domain_jump_realign",
		"address"     : 8407262,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"icc_cfg",
		"address"     : 8407263,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"qsfp_i2c_reg",
		"address"     : 8407264,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"sfp_address_set",
		"address"     : 8407265,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"tag_now",
		"address"     : 8407266,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	]
}