d = { "name" : "scllrfPRC",
	'registers': [
	{	"name" :"Hell",
		"address"     : 0,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"O_Wo",
		"address"     : 1,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Rld_",
		"address"     : 2,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"H0D0A0D0A",
		"address"     : 3,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Llspi_Status",
		"address"     : 4,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Llspi_Result",
		"address"     : 5,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Clk_Status_Out",
		"address"     : 6,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Ffffffff",
		"address"     : 7,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Frequency_Adc",
		"address"     : 8,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Frequency_4Xout",
		"address"     : 9,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Frequency_Clkout3",
		"address"     : 10,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Frequency_Dco",
		"address"     : 11,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U2DoutBits31to0",
		"address"     : 12,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U2DoutBits63to32",
		"address"     : 13,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Idelay_Value_Out_U2Bits19to0",
		"address"     : 14,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Idelay_Value_Out_U2Bits39to20",
		"address"     : 15,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U3DoutBits31to0",
		"address"     : 16,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U3DoutBits63to32",
		"address"     : 17,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Idelay_Value_Out_U3Bits19to0",
		"address"     : 18,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Idelay_Value_Out_U3Bits39to20",
		"address"     : 19,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Wave0_Out",
		"address"     : 20,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Wave1_Out",
		"address"     : 21,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Wave1_Out",
		"address"     : 22,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Wave2_Out",
		"address"     : 23,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Wave3_Out",
		"address"     : 24,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Wave4_Out",
		"address"     : 25,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Ctrace_Running",
		"address"     : 28,
		"bit_width"      : 14,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Frequency_Gtx_Tx",
		"address"     : 29,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Frequency_Gtx_Rx",
		"address"     : 30,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Hist_Status",
		"address"     : 31,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Phasex_Status",
		"address"     : 46,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Clk_Phase_Diff_Out_U2",
		"address"     : 47,
		"bit_width"      : 13,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Clk_Phase_Diff_Out_U3",
		"address"     : 48,
		"bit_width"      : 13,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Crc_Errors",
		"address"     : 49,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_Sdo_Addr",
		"address"     : 56,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"_U15_Spi_Rdbk",
		"address"     : 56,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_Spi_Ready",
		"address"     : 57,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_Sdio_As_Sdo",
		"address"     : 57,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U18_Sdo_Addr",
		"address"     : 60,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"_U18_Spi_Rdbk",
		"address"     : 60,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U18_Sdio_As_Sdo",
		"address"     : 61,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"U18_Spi_Ready",
		"address"     : 61,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Trig_Cnt",
		"address"     : 64,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Waveforms_Available",
		"address"     : 65,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Banyan_Status",
		"address"     : 66,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Slow_Chain_Out",
		"address"     : 67,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Trace_Status1",
		"address"     : 68,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Trace_Status2",
		"address"     : 69,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Llrf_Circle_Ready",
		"address"     : 70,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Idelay_Base",
		"address"     : 112,
		"bit_width"      : 7,
		"nelm"      : 16,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Hist_Dout",
		"address"     : 1048576,
		"bit_width"      : 16,
		"nelm"      : 65536,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Phasex_Dout",
		"address"     : 1114112,
		"bit_width"      : 16,
		"nelm"      : 1024,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Banyan_Buf",
		"address"     : 1179648,
		"bit_width"      : 32,
		"nelm"      : 65536,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Scanner_Result",
		"address"     : 1245184,
		"bit_width"      : 8,
		"nelm"      : 2048,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Trace_Iq_Buf",
		"address"     : 1310720,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"Trace_I_Buf",
		"address"     : 1343488,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"Trace_Q_Buf",
		"address"     : 1359872,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"Qsfp_Buf",
		"address"     : 1388544,
		"bit_width"      : 8,
		"nelm"      : 256,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Llrf_Circle_Data",
		"address"     : 1507328,
		"bit_width"      : 16,
		"nelm"      : 4096,
		"access"      : "r",
		"signed"      : "signed"
	},
	{	"name" :"Shell_0_Slow_Data",
		"address"     : 1572864,
		"bit_width"      : 8,
		"nelm"      : 128,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell_1_Slow_Data",
		"address"     : 1638400,
		"bit_width"      : 8,
		"nelm"      : 128,
		"access"      : "r",
		"signed"      : "unsigned"
	},
	{	"name" :"Noise_CoupleK_Out",
		"address"     : 8388608,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Prop_Const",
		"address"     : 8389632,
		"bit_width"      : 21,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0Cav4_ElecDot0K_Out",
		"address"     : 8390656,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecDot1K_Out",
		"address"     : 8391680,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Cav4_ElecDot2K_Out",
		"address"     : 8392704,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"DigdspRsmCav0Cav4_ElecOuter_Prod0K_Out",
		"address"     : 8393728,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Cav4_ElecOuter_Prod1K_Out",
		"address"     : 8394752,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecOuter_Prod2K_Out",
		"address"     : 8395776,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Piezo_CoupleK_Out",
		"address"     : 8396800,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecDot0K_Out",
		"address"     : 8397824,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecDot1K_Out",
		"address"     : 8398848,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecDot2K_Out",
		"address"     : 8399872,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav1Cav4_ElecOuter_Prod0K_Out",
		"address"     : 8400896,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecOuter_Prod1K_Out",
		"address"     : 8401920,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecOuter_Prod2K_Out",
		"address"     : 8402944,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Piezo_CoupleK_Out",
		"address"     : 8403968,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Delay_Pc_Xxx",
		"address"     : 8404992,
		"bit_width"      : 32,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1Delay_Pc_Xxx",
		"address"     : 8406016,
		"bit_width"      : 32,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspPiezoSf_Consts",
		"address"     : 8407040,
		"bit_width"      : 20,
		"nelm"      : 8,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"RsmShell1DspPiezoSf_Consts",
		"address"     : 8407048,
		"bit_width"      : 20,
		"nelm"      : 8,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell0DspFdbk_CoreMp_ProcCoeff",
		"address"     : 8407056,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0DspFdbk_CoreMp_ProcLim",
		"address"     : 8407060,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0DspFdbk_CoreMp_ProcSetmp",
		"address"     : 8407064,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"DigdspRsmShell1DspFdbk_CoreMp_ProcCoeff",
		"address"     : 8407068,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1DspFdbk_CoreMp_ProcLim",
		"address"     : 8407072,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Shell1DspFdbk_CoreMp_ProcSetmp",
		"address"     : 8407076,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecDrive_CoupleOut_Coupling",
		"address"     : 8407080,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav0Cav4_ElecDrive_CoupleOphoff",
		"address"     : 8407082,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Cav4_ElecMode0OcoupOut_Coupling",
		"address"     : 8407084,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav0Cav4_ElecMode0OcoupOphoff",
		"address"     : 8407086,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Cav4_ElecMode1OcoupOut_Coupling",
		"address"     : 8407088,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Cav4_ElecMode1OcoupOphoff",
		"address"     : 8407090,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode2OcoupOut_Coupling",
		"address"     : 8407092,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode2OcoupOphoff",
		"address"     : 8407094,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecDrive_CoupleOut_Coupling",
		"address"     : 8407096,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecDrive_CoupleOphoff",
		"address"     : 8407098,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode0OcoupOut_Coupling",
		"address"     : 8407100,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecMode0OcoupOphoff",
		"address"     : 8407102,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecMode1OcoupOut_Coupling",
		"address"     : 8407104,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode1OcoupOphoff",
		"address"     : 8407106,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav1Cav4_ElecMode2OcoupOut_Coupling",
		"address"     : 8407108,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode2OcoupOphoff",
		"address"     : 8407110,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"DigdspRsmShell0DspLp_NotchLp1AKx",
		"address"     : 8407112,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0DspLp_NotchLp1AKy",
		"address"     : 8407114,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmShell0DspLp_NotchLp1BKx",
		"address"     : 8407116,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0DspLp_NotchLp1BKy",
		"address"     : 8407118,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1DspLp_NotchLp1AKx",
		"address"     : 8407120,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"AtopDigdspRsmShell1DspLp_NotchLp1AKy",
		"address"     : 8407122,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1DspLp_NotchLp1BKx",
		"address"     : 8407124,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1DspLp_NotchLp1BKy",
		"address"     : 8407126,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Adc_Mmcm",
		"address"     : 8407128,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_Spi_Data_Addr_R",
		"address"     : 8407129,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"U15_Spi_Read_And_Start_R",
		"address"     : 8407130,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigcfgU18_Spi_Data_Addr_R",
		"address"     : 8407131,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigcfgU18_Spi_Read_And_Start_R",
		"address"     : 8407132,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"AtopDigcfgU2_Clk_Reset_R",
		"address"     : 8407133,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"U2_Iserdes_Reset_R",
		"address"     : 8407134,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"U3_Clk_Reset_R",
		"address"     : 8407135,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"U3_Iserdes_Reset_R",
		"address"     : 8407136,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigcfgU4_Reset_R",
		"address"     : 8407137,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Banyan_Mask",
		"address"     : 8407138,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Bitslip",
		"address"     : 8407139,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Clk_Status_We",
		"address"     : 8407140,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigcfgIdelayctrl_Reset_R",
		"address"     : 8407141,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Llspi_We",
		"address"     : 8407142,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Mmcm_Reset_R",
		"address"     : 8407143,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Periph_Config",
		"address"     : 8407144,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Phasex_Trig",
		"address"     : 8407145,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigcfgRawadc_Trig",
		"address"     : 8407146,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Scan_Trigger_We",
		"address"     : 8407147,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Scanner_Debug",
		"address"     : 8407148,
		"bit_width"      : 5,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Sync_Ad7794_Cset",
		"address"     : 8407149,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigcfgSync_Tps62210_Cset",
		"address"     : 8407150,
		"bit_width"      : 6,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Mode",
		"address"     : 8407151,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Adc_Test_Reset",
		"address"     : 8407152,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigdspAmplitude",
		"address"     : 8407153,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Average_Len",
		"address"     : 8407154,
		"bit_width"      : 30,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Buf_Trig",
		"address"     : 8407155,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cic_Period",
		"address"     : 8407156,
		"bit_width"      : 14,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cic_Shift",
		"address"     : 8407157,
		"bit_width"      : 4,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Circle_Buf_Flip",
		"address"     : 8407158,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Dac_Dds_Reset",
		"address"     : 8407159,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigdspDac_Mode",
		"address"     : 8407160,
		"bit_width"      : 4,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Ddsa_Modulo",
		"address"     : 8407161,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Ddsa_Phstep_H",
		"address"     : 8407162,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigdspDdsa_Phstep_L",
		"address"     : 8407163,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Hist_Count_W_Strobe",
		"address"     : 8407164,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Llrf_Dsp_Dac_En",
		"address"     : 8407165,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Lo_Amp",
		"address"     : 8407166,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigdspModulo",
		"address"     : 8407167,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigdspPhase_Step_H",
		"address"     : 8407168,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Phase_Step_L",
		"address"     : 8407169,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav_Sel",
		"address"     : 8407170,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Prl_Cfg",
		"address"     : 8407171,
		"bit_width"      : 9,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Prc_DspPrl_Gain",
		"address"     : 8407172,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Beam0Modulo",
		"address"     : 8407173,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"RsmBeam0Phase_Init",
		"address"     : 8407174,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0Phase_Step",
		"address"     : 8407175,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1Modulo",
		"address"     : 8407176,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1Phase_Init",
		"address"     : 8407177,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"RsmBeam1Phase_Step",
		"address"     : 8407178,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav4_MechPrngIva",
		"address"     : 8407179,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"RsmCav4_MechPrngIvb",
		"address"     : 8407180,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav4_MechPrngRandom_Run",
		"address"     : 8407181,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav0A_CavOffs",
		"address"     : 8407182,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0A_ForOffs",
		"address"     : 8407183,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0A_RflOffs",
		"address"     : 8407184,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Amp_LpBw",
		"address"     : 8407185,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecFq0Coarse_Freq",
		"address"     : 8407186,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecFq1Coarse_Freq",
		"address"     : 8407187,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecFq2Coarse_Freq",
		"address"     : 8407188,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav0Cav4_ElecMode0Beam_Coupling",
		"address"     : 8407189,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode0Bw",
		"address"     : 8407190,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode0Drive_Coupling",
		"address"     : 8407191,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"AtopDigdspRsmCav0Cav4_ElecMode1Beam_Coupling",
		"address"     : 8407192,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav0Cav4_ElecMode1Bw",
		"address"     : 8407193,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode1Drive_Coupling",
		"address"     : 8407194,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"AtopDigdspRsmCav0Cav4_ElecMode2Beam_Coupling",
		"address"     : 8407195,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode2Bw",
		"address"     : 8407196,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecMode2Drive_Coupling",
		"address"     : 8407197,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C0Cav4_ElecModulo",
		"address"     : 8407198,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav0Cav4_ElecPhase_Step",
		"address"     : 8407199,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0ComprSat_Ctl",
		"address"     : 8407200,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav0PrngIva",
		"address"     : 8407201,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0PrngIvb",
		"address"     : 8407202,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0PrngRandom_Run",
		"address"     : 8407203,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1A_CavOffs",
		"address"     : 8407204,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"DigdspRsmCav1A_ForOffs",
		"address"     : 8407205,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1A_RflOffs",
		"address"     : 8407206,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav1Amp_LpBw",
		"address"     : 8407207,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecFq0Coarse_Freq",
		"address"     : 8407208,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecFq1Coarse_Freq",
		"address"     : 8407209,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecFq2Coarse_Freq",
		"address"     : 8407210,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode0Beam_Coupling",
		"address"     : 8407211,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecMode0Bw",
		"address"     : 8407212,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode0Drive_Coupling",
		"address"     : 8407213,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode1Beam_Coupling",
		"address"     : 8407214,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav1Cav4_ElecMode1Bw",
		"address"     : 8407215,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecMode1Drive_Coupling",
		"address"     : 8407216,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"RsmCav1Cav4_ElecMode2Beam_Coupling",
		"address"     : 8407217,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Cav1Cav4_ElecMode2Bw",
		"address"     : 8407218,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1Cav4_ElecModulo",
		"address"     : 8407220,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1Cav4_ElecPhase_Step",
		"address"     : 8407221,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"RsmCav1ComprSat_Ctl",
		"address"     : 8407222,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1PrngIva",
		"address"     : 8407223,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Cav1PrngIvb",
		"address"     : 8407224,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1PrngRandom_Run",
		"address"     : 8407225,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"RsmDac_Iq_Phase",
		"address"     : 8407226,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspChan_Keep",
		"address"     : 8407227,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspFdbk_CoreCoarse_Scale",
		"address"     : 8407228,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell0DspFdbk_CoreMp_ProcPh_Offset",
		"address"     : 8407229,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Shell0DspFdbk_CoreMp_ProcSel_En",
		"address"     : 8407230,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspFdbk_CoreMp_ProcSel_Thresh",
		"address"     : 8407231,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"Shell0DspModulo",
		"address"     : 8407232,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell0DspPhase_Step",
		"address"     : 8407233,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspPiezoPiezo_Dc",
		"address"     : 8407234,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell0DspTag",
		"address"     : 8407235,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspUse_Fiber_Iq",
		"address"     : 8407236,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspWave_Samp_Per",
		"address"     : 8407237,
		"bit_width"      : 7,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C0DspWave_Shift",
		"address"     : 8407238,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell1DspChan_Keep",
		"address"     : 8407239,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspFdbk_CoreCoarse_Scale",
		"address"     : 8407240,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspFdbk_CoreMp_ProcPh_Offset",
		"address"     : 8407241,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1DspFdbk_CoreMp_ProcSel_En",
		"address"     : 8407242,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspFdbk_CoreMp_ProcSel_Thresh",
		"address"     : 8407243,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"C1DspModulo",
		"address"     : 8407244,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspPhase_Step",
		"address"     : 8407245,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspPiezoPiezo_Dc",
		"address"     : 8407246,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspTag",
		"address"     : 8407247,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspUse_Fiber_Iq",
		"address"     : 8407248,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"C1DspWave_Samp_Per",
		"address"     : 8407249,
		"bit_width"      : 7,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Shell1DspWave_Shift",
		"address"     : 8407250,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"AtopDigdspRewind",
		"address"     : 8407251,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Ampstep",
		"address"     : 8407252,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Ssa_Stim_En",
		"address"     : 8407253,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Ssa_StimG_Period",
		"address"     : 8407254,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Ssa_StimPertstep",
		"address"     : 8407255,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"DigdspTrace_Keep",
		"address"     : 8407256,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Trace_Reset_We",
		"address"     : 8407257,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Trig_Internal",
		"address"     : 8407258,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Trig_Mode",
		"address"     : 8407259,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Wave0_Src",
		"address"     : 8407260,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Wave1_Src",
		"address"     : 8407261,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Domain_Jump_Realign",
		"address"     : 8407262,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Icc_Cfg",
		"address"     : 8407263,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Qsfp_I2C_Reg",
		"address"     : 8407264,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Sfp_Address_Set",
		"address"     : 8407265,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"Tag_Now",
		"address"     : 8407266,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	]
}