d = { "name" : "scllrfPRC",
	'registers': [
	{	"name" :"Hell",
		"address"     : 0,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"o_wo",
		"address"     : 1,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"rld_",
		"address"     : 2,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"h0d0a0d0a",
		"address"     : 3,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"llspi_status",
		"address"     : 4,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"llspi_result",
		"address"     : 5,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"ffffffff",
		"address"     : 7,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"fquency_adc",
		"address"     : 8,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"fquency_4xout",
		"address"     : 9,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"fquency_clkout3",
		"address"     : 10,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"fquency_dco",
		"address"     : 11,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U2doutBits31to0",
		"address"     : 12,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U2doutBits63to32",
		"address"     : 13,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"idelay_value_out_U2Bits19to0",
		"address"     : 14,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"idelay_value_out_U2Bits39to20",
		"address"     : 15,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U3doutBits31to0",
		"address"     : 16,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U3doutBits63to32",
		"address"     : 17,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"idelay_value_out_U3Bits19to0",
		"address"     : 18,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"idelay_value_out_U3Bits39to20",
		"address"     : 19,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"wv0_out",
		"address"     : 20,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"wv1_out",
		"address"     : 21,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"adc_test_wv1_out",
		"address"     : 22,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"adc_test_wv2_out",
		"address"     : 23,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"adc_test_wv3_out",
		"address"     : 24,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"adc_test_wv4_out",
		"address"     : 25,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"ctrace_running",
		"address"     : 28,
		"bit_width"      : 14,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"fquency_gtx_tx",
		"address"     : 29,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"fquency_gtx_rx",
		"address"     : 30,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"hist_status",
		"address"     : 31,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"phx_status",
		"address"     : 46,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"clk_ph_diff_out_U2",
		"address"     : 47,
		"bit_width"      : 13,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"clk_ph_diff_out_U3",
		"address"     : 48,
		"bit_width"      : 13,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"crc_errors",
		"address"     : 49,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"_U15_spi_rdbk",
		"address"     : 56,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U15_sdo_addr",
		"address"     : 56,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U15_spi_ready",
		"address"     : 57,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U15_sdio_as_sdo",
		"address"     : 57,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U18_sdo_addr",
		"address"     : 60,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"_U18_spi_rdbk",
		"address"     : 60,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U18_sdio_as_sdo",
		"address"     : 61,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"U18_spi_ready",
		"address"     : 61,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"adc_test_trig_cnt",
		"address"     : 64,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"wvforms_available",
		"address"     : 65,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"banyan_status",
		"address"     : 66,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"slow_chain_out",
		"address"     : 67,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"trace_status1",
		"address"     : 68,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"trace_status2",
		"address"     : 69,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "r",
	},
	{	"name" :"idelay_base",
		"address"     : 112,
		"bit_width"      : 7,
		"nelm"      : 16,
		"access"      : "r",
	},
	{	"name" :"hist_dout",
		"address"     : 1048576,
		"bit_width"      : 16,
		"nelm"      : 65536,
		"access"      : "r",
	},
	{	"name" :"phx_dout",
		"address"     : 1114112,
		"bit_width"      : 16,
		"nelm"      : 1024,
		"access"      : "r",
	},
	{	"name" :"banyan_buf",
		"address"     : 1179648,
		"bit_width"      : 32,
		"nelm"      : 65536,
		"access"      : "r",
	},
	{	"name" :"scanner_result",
		"address"     : 1245184,
		"bit_width"      : 8,
		"nelm"      : 2048,
		"access"      : "r",
	},
	{	"name" :"trace_iq_buf",
		"address"     : 1310720,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
	},
	{	"name" :"trace_i_buf",
		"address"     : 1343488,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
	},
	{	"name" :"trace_q_buf",
		"address"     : 1359872,
		"bit_width"      : 32,
		"nelm"      : 16384,
		"access"      : "r",
	},
	{	"name" :"qsfp_buf",
		"address"     : 1388544,
		"bit_width"      : 8,
		"nelm"      : 256,
		"access"      : "r",
	},
	{	"name" :"dig_dsp_rsm_c4_mech_noise_cpl_k_out",
		"address"     : 8388608,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c4_mech_resnr_prop_const",
		"address"     : 8389632,
		"bit_width"      : 21,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_dot_0_k_out",
		"address"     : 8390656,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_dot_1_k_out",
		"address"     : 8391680,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_dot_2_k_out",
		"address"     : 8392704,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_outer_prod_0_k_out",
		"address"     : 8393728,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_outer_prod_1_k_out",
		"address"     : 8394752,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_outer_prod_2_k_out",
		"address"     : 8395776,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_piezo_cpl_k_out",
		"address"     : 8396800,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_dot_0_k_out",
		"address"     : 8397824,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_dot_1_k_out",
		"address"     : 8398848,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_dot_2_k_out",
		"address"     : 8399872,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_outer_prod_0_k_out",
		"address"     : 8400896,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_outer_prod_1_k_out",
		"address"     : 8401920,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_outer_prod_2_k_out",
		"address"     : 8402944,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_piezo_cpl_k_out",
		"address"     : 8403968,
		"bit_width"      : 18,
		"nelm"      : 1024,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_mp_proc_coeff",
		"address"     : 8404992,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_mp_proc_lim",
		"address"     : 8404996,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_mp_proc_setmp",
		"address"     : 8405000,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_mp_proc_coeff",
		"address"     : 8405004,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_mp_proc_lim",
		"address"     : 8405008,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_mp_proc_setmp",
		"address"     : 8405012,
		"bit_width"      : 18,
		"nelm"      : 4,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_edco_cpl",
		"address"     : 8405016,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_edco_ph_offset",
		"address"     : 8405018,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_edco_cpl",
		"address"     : 8405020,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_edco_ph_offset",
		"address"     : 8405022,
		"bit_width"      : 19,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_lp_notch_lp1a_kx",
		"address"     : 8405024,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_lp_notch_lp1a_ky",
		"address"     : 8405026,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_lp_notch_lp1b_kx",
		"address"     : 8405028,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_lp_notch_lp1b_ky",
		"address"     : 8405030,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_lp_notch_lp1a_kx",
		"address"     : 8405032,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_lp_notch_lp1a_ky",
		"address"     : 8405034,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_lp_notch_lp1b_kx",
		"address"     : 8405036,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_lp_notch_lp1b_ky",
		"address"     : 8405038,
		"bit_width"      : 18,
		"nelm"      : 2,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"adc_mmcm",
		"address"     : 8405040,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U15_spi_data_addr_r",
		"address"     : 8405041,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U15_spi_read_and_start_r",
		"address"     : 8405042,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U18_spi_data_addr_r",
		"address"     : 8405043,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U18_spi_read_and_start_r",
		"address"     : 8405044,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U2_clk_reset_r",
		"address"     : 8405045,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U2_iserdes_reset_r",
		"address"     : 8405046,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U3_clk_reset_r",
		"address"     : 8405047,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U3_iserdes_reset_r",
		"address"     : 8405048,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_U4_reset_r",
		"address"     : 8405049,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_banyan_mask",
		"address"     : 8405050,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_bitslip",
		"address"     : 8405051,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_idelayctrl_reset_r",
		"address"     : 8405052,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_llspi_we",
		"address"     : 8405053,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_mmcm_reset_r",
		"address"     : 8405054,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_periph_config",
		"address"     : 8405055,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_phx_trig",
		"address"     : 8405056,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_rawadc_trig",
		"address"     : 8405057,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_scan_trigger_we",
		"address"     : 8405058,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_scanner_debug",
		"address"     : 8405059,
		"bit_width"      : 5,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_sync_ad7794_cset",
		"address"     : 8405060,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_cfg_sync_tps62210_cset",
		"address"     : 8405061,
		"bit_width"      : 6,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_adc_test_md",
		"address"     : 8405062,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_adc_test_reset",
		"address"     : 8405063,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_amplitude",
		"address"     : 8405064,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_average_len",
		"address"     : 8405065,
		"bit_width"      : 30,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_buf_trig",
		"address"     : 8405066,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_cic_period",
		"address"     : 8405067,
		"bit_width"      : 14,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_cic_shift",
		"address"     : 8405068,
		"bit_width"      : 4,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_circle_buf_flip",
		"address"     : 8405069,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_dac_dds_reset",
		"address"     : 8405070,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_dac_md",
		"address"     : 8405071,
		"bit_width"      : 4,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ddsa_mod",
		"address"     : 8405072,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ddsa_phstep_h",
		"address"     : 8405073,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ddsa_phstep_l",
		"address"     : 8405074,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_hist_count_w_strobe",
		"address"     : 8405075,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_llrf_dsp_dac_en",
		"address"     : 8405076,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_lo_amp",
		"address"     : 8405077,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_mod",
		"address"     : 8405078,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ph_step_h",
		"address"     : 8405079,
		"bit_width"      : 20,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ph_step_l",
		"address"     : 8405080,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_prc_dsp_csel",
		"address"     : 8405081,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_prc_dsp_prl_cfg",
		"address"     : 8405082,
		"bit_width"      : 9,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_prc_dsp_prl_gain",
		"address"     : 8405083,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_beam_0_mod",
		"address"     : 8405084,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_beam_0_ph_init",
		"address"     : 8405085,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_beam_0_ph_step",
		"address"     : 8405086,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_beam_1_mod",
		"address"     : 8405087,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_beam_1_ph_init",
		"address"     : 8405088,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_beam_1_ph_step",
		"address"     : 8405089,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c4_mech_prng_iva",
		"address"     : 8405090,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c4_mech_prng_ivb",
		"address"     : 8405091,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c4_mech_prng_rnd_run",
		"address"     : 8405092,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_a_coffset",
		"address"     : 8405093,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_a_for_offset",
		"address"     : 8405094,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_a_rfl_offset",
		"address"     : 8405095,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_amp_lp_bw",
		"address"     : 8405096,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_efrq_0_crs_fq",
		"address"     : 8405097,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_efrq_1_crs_fq",
		"address"     : 8405098,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_efrq_2_crs_fq",
		"address"     : 8405099,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_0_beam_cpl",
		"address"     : 8405100,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_0_bw",
		"address"     : 8405101,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_0_drv_cpl",
		"address"     : 8405102,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_1_beam_cpl",
		"address"     : 8405103,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_1_bw",
		"address"     : 8405104,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_1_drv_cpl",
		"address"     : 8405105,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_2_beam_cpl",
		"address"     : 8405106,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_2_bw",
		"address"     : 8405107,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_emode_2_drv_cpl",
		"address"     : 8405108,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_mod",
		"address"     : 8405109,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_c4_elec_ph_step",
		"address"     : 8405110,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_compr_sat_ctl",
		"address"     : 8405111,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_prng_iva",
		"address"     : 8405112,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_prng_ivb",
		"address"     : 8405113,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c0_prng_rnd_run",
		"address"     : 8405114,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c1_a_coffset",
		"address"     : 8405115,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_a_for_offset",
		"address"     : 8405116,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_a_rfl_offset",
		"address"     : 8405117,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_amp_lp_bw",
		"address"     : 8405118,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_efrq_0_crs_fq",
		"address"     : 8405119,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_efrq_1_crs_fq",
		"address"     : 8405120,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_efrq_2_crs_fq",
		"address"     : 8405121,
		"bit_width"      : 28,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_0_beam_cpl",
		"address"     : 8405122,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_0_bw",
		"address"     : 8405123,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_0_drv_cpl",
		"address"     : 8405124,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_1_beam_cpl",
		"address"     : 8405125,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_1_bw",
		"address"     : 8405126,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_1_drv_cpl",
		"address"     : 8405127,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_2_beam_cpl",
		"address"     : 8405128,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_2_bw",
		"address"     : 8405129,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_emode_2_drv_cpl",
		"address"     : 8405130,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_mod",
		"address"     : 8405131,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c1_c4_elec_ph_step",
		"address"     : 8405132,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c1_compr_sat_ctl",
		"address"     : 8405133,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c1_prng_iva",
		"address"     : 8405134,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c1_prng_ivb",
		"address"     : 8405135,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_c1_prng_rnd_run",
		"address"     : 8405136,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_dac_iq_ph",
		"address"     : 8405137,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_chan_keep",
		"address"     : 8405138,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_crs_scale",
		"address"     : 8405139,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_mp_proc_ph_offset",
		"address"     : 8405140,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_mp_proc_sel_en",
		"address"     : 8405141,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_fdbk_mp_proc_sel_thresh",
		"address"     : 8405142,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_mod",
		"address"     : 8405143,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_ph_step",
		"address"     : 8405144,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_piezo_piezo_dc",
		"address"     : 8405145,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_tag",
		"address"     : 8405146,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_use_fiber_iq",
		"address"     : 8405147,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_wv_samp_per",
		"address"     : 8405148,
		"bit_width"      : 7,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh0_dsp_wv_shift",
		"address"     : 8405149,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_chan_keep",
		"address"     : 8405150,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_crs_scale",
		"address"     : 8405151,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_mp_proc_ph_offset",
		"address"     : 8405152,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_mp_proc_sel_en",
		"address"     : 8405153,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_fdbk_mp_proc_sel_thresh",
		"address"     : 8405154,
		"bit_width"      : 18,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "signed"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_mod",
		"address"     : 8405155,
		"bit_width"      : 12,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_ph_step",
		"address"     : 8405156,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_piezo_piezo_dc",
		"address"     : 8405157,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_tag",
		"address"     : 8405158,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_use_fiber_iq",
		"address"     : 8405159,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_wv_samp_per",
		"address"     : 8405160,
		"bit_width"      : 7,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rsm_sh1_dsp_wv_shift",
		"address"     : 8405161,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_rewind",
		"address"     : 8405162,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_ampstep",
		"address"     : 8405163,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_en",
		"address"     : 8405164,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_g_period",
		"address"     : 8405165,
		"bit_width"      : 10,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_ssa_stim_pertstep",
		"address"     : 8405166,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trace_keep",
		"address"     : 8405167,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trace_reset_we",
		"address"     : 8405168,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trig_internal",
		"address"     : 8405169,
		"bit_width"      : 1,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_trig_md",
		"address"     : 8405170,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_wv0_src",
		"address"     : 8405171,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"dig_dsp_wv1_src",
		"address"     : 8405172,
		"bit_width"      : 3,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"domain_jump_realign",
		"address"     : 8405173,
		"bit_width"      : 2,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"icc_cfg",
		"address"     : 8405174,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"qsfp_i2c_reg",
		"address"     : 8405175,
		"bit_width"      : 32,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"sfp_address_set",
		"address"     : 8405176,
		"bit_width"      : 16,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	{	"name" :"tag_now",
		"address"     : 8405177,
		"bit_width"      : 8,
		"nelm"      : 1,
		"access"      : "rw",
		"signed"      : "unsigned"
	},
	]
}