/**
 *-----------------------------------------------------------------------------
 * Title      : superconducting low level RF EPICS interface
 * ----------------------------------------------------------------------------
 * File       : scllrfAsynPortDriver.h
 * Author     : Garth Brown, gwbrown@slac.stanford.edu
 * Created    : June 17, 2016
 * Last update: September 6, 2016
 * ----------------------------------------------------------------------------
 * Description:
 * Prototype for FPGA register access to FPGAs using protocol defined in papers
 * given to SLAC by LBNL (Larry Doolittle). Uses asynPortDriver interface. Some of this
 * should eventually be autogenerated from json files or some such, and templates.
 *
 * ----------------------------------------------------------------------------
 * This file is part of LCLS II. It is subject to
 * the license terms in the LICENSE.txt file found in the top-level directory
 * of this distribution and at:
    * https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
 * No part of LCLS II, including this file, may be
 * copied, modified, propagated, or distributed except according to the terms
 * contained in the LICENSE.txt file.
 * ----------------------------------------------------------------------------
**/
#include "scllrfAsynPortDriver.h"


// Waveform data is packed as 2D arrays, not one after the other
// in the network data. See cmoc code "submodules/common_hdl/circle.txt" for more details.
// Summary: (array 1, data 1 and 2), (array 2, data 1 and 2), (array 3, data 1 and 2)....
// Addressing: I/Q waveforms base address = 0x140000
	// additional base offsets, calculated from npt = 1 << ((trace_status >> 24) & 0x3F)
	//   0 * npt  16-bit I and Q
	//   1 * npt  16-bit I and Q
	//   2 * npt  22-bit I
	//   3 * npt  22-bit Q
static const uint32_t wavesStart = 0x140000; // From FPGA design, base address
static const uint32_t wavesEnd = 0x14ffff; // max possible
static const unsigned waveBufferRegCount = wavesEnd - wavesStart + 1;
static const unsigned maxWavesCount = 8; // max channels, max number of waveforms interlaced in waveform buffer
static const unsigned waveBuffSize = waveBufferRegCount/4 + waveBufferRegCount/maxMsgSize; // divide by number of buffers
/**< Waveform buffer is read in waveSegmentCount segments due to network packet size limits.
 *  1+ is an approximation of "round upwards". -sizeof(FpgaReg) makes space for the nonce */
static const unsigned waveSegmentCount = 1 + (sizeof(FpgaReg) * waveBuffSize)
				/ (maxMsgSize - sizeof(FpgaReg));

/**< Size of each segment, in number of registers */
static const unsigned waveSegmentSize = 1
		+ (waveBuffSize + waveSegmentCount) / waveSegmentCount;

/* Registers */
static const char *x0D0A0D0ARString = "0D0A0D0A_R";
static const char *HellRString = "HELL_R";
static const char *U15SdioAsSdoRString = "U15_SDIO_AS_SDO_R";
static const char *U15SdoAddrRString = "U15_SDO_ADDR_R";
static const char *U15SpiAddrRRString = "U15_SPI_ADDR_R_R";
static const char *U15SpiAddrRWString = "U15_SPI_ADDR_R_W";
static const char *U15SpiDataRRString = "U15_SPI_DATA_R_R";
static const char *U15SpiDataRWString = "U15_SPI_DATA_R_W";
static const char *U15SpiReadRRString = "U15_SPI_READ_R_R";
static const char *U15SpiReadRWString = "U15_SPI_READ_R_W";
static const char *U15SpiReadyRString = "U15_SPI_READY_R";
static const char *U15SpiStartRRString = "U15_SPI_START_R_R";
static const char *U15SpiStartRWString = "U15_SPI_START_R_W";
static const char *U18SdioAsSdoRString = "U18_SDIO_AS_SDO_R";
static const char *U18SdoAddrRString = "U18_SDO_ADDR_R";
static const char *U18SpiAddrRRString = "U18_SPI_ADDR_R_R";
static const char *U18SpiAddrRWString = "U18_SPI_ADDR_R_W";
static const char *U18SpiDataRRString = "U18_SPI_DATA_R_R";
static const char *U18SpiDataRWString = "U18_SPI_DATA_R_W";
static const char *U18SpiReadRRString = "U18_SPI_READ_R_R";
static const char *U18SpiReadRWString = "U18_SPI_READ_R_W";
static const char *U18SpiReadyRString = "U18_SPI_READY_R";
static const char *U18SpiStartRRString = "U18_SPI_START_R_R";
static const char *U18SpiStartRWString = "U18_SPI_START_R_W";
static const char *U2ClkResetRWString = "U2_CLK_RESET_R_W";
static const char *U2IserdesResetRWString = "U2_ISERDES_RESET_R_W";
static const char *U2Doutbits31To0RString = "U2DOUTBITS31TO0_R";
static const char *U2Doutbits63To32RString = "U2DOUTBITS63TO32_R";
static const char *U3ClkResetRWString = "U3_CLK_RESET_R_W";
static const char *U3IserdesResetRWString = "U3_ISERDES_RESET_R_W";
static const char *U3Doutbits31To0RString = "U3DOUTBITS31TO0_R";
static const char *U3Doutbits63To32RString = "U3DOUTBITS63TO32_R";
static const char *U15SpiRdbkRString = "U15_SPI_RDBK_R";
static const char *U18SpiRdbkRString = "U18_SPI_RDBK_R";
static const char *AdcTestModeRString = "ADC_TEST_MODE_R";
static const char *AdcTestModeWString = "ADC_TEST_MODE_W";
static const char *AdcTestResetWString = "ADC_TEST_RESET_W";
static const char *AdcTestTrigCntRString = "ADC_TEST_TRIG_CNT_R";
static const char *AdcTestWave1OutRString = "ADC_TEST_WAVE1_OUT_R";
static const char *AdcTestWave2OutRString = "ADC_TEST_WAVE2_OUT_R";
static const char *AdcTestWave3OutRString = "ADC_TEST_WAVE3_OUT_R";
static const char *AdcTestWave4OutRString = "ADC_TEST_WAVE4_OUT_R";
static const char *AmplitudeRString = "AMPLITUDE_R";
static const char *AmplitudeWString = "AMPLITUDE_W";
static const char *AverageLenRString = "AVERAGE_LEN_R";
static const char *AverageLenWString = "AVERAGE_LEN_W";
static const char *BanyanBufRString = "BANYAN_BUF_R";
static const char *BanyanMaskRString = "BANYAN_MASK_R";
static const char *BanyanMaskWString = "BANYAN_MASK_W";
static const char *BanyanStatusRString = "BANYAN_STATUS_R";
static const char *BitslipWString = "BITSLIP_W";
static const char *BufTrigWString = "BUF_TRIG_W";
static const char *CicPeriodRString = "CIC_PERIOD_R";
static const char *CicPeriodWString = "CIC_PERIOD_W";
static const char *CicShiftRString = "CIC_SHIFT_R";
static const char *CicShiftWString = "CIC_SHIFT_W";
static const char *ClkPhaseDiffOutU2RString = "CLK_PHASE_DIFF_OUT_U2_R";
static const char *ClkPhaseDiffOutU3RString = "CLK_PHASE_DIFF_OUT_U3_R";
static const char *DacDdsResetWString = "DAC_DDS_RESET_W";
static const char *DacModeRString = "DAC_MODE_R";
static const char *DacModeWString = "DAC_MODE_W";
static const char *DdsaModuloRString = "DDSA_MODULO_R";
static const char *DdsaModuloWString = "DDSA_MODULO_W";
static const char *DdsaPhstepHRString = "DDSA_PHSTEP_H_R";
static const char *DdsaPhstepHWString = "DDSA_PHSTEP_H_W";
static const char *DdsaPhstepLRString = "DDSA_PHSTEP_L_R";
static const char *DdsaPhstepLWString = "DDSA_PHSTEP_L_W";
static const char *FfffffffRString = "FFFFFFFF_R";
static const char *Frequency4XoutRString = "FREQUENCY_4XOUT_R";
static const char *FrequencyClkout3RString = "FREQUENCY_CLKOUT3_R";
static const char *FrequencyDcoRString = "FREQUENCY_DCO_R";
static const char *FrequencyRString = "FREQUENCY_R";
static const char *HistCountWString = "HIST_COUNT_W";
static const char *HistDoutRString = "HIST_DOUT_R";
static const char *HistStatusRString = "HIST_STATUS_R";
static const char *HwResetRString = "HW_RESET_R";
static const char *HwResetWString = "HW_RESET_W";
static const char *Idelay0RString = "IDELAY_0_R";
static const char *Idelay0WString = "IDELAY_0_W";
static const char *Idelay10RString = "IDELAY_10_R";
static const char *Idelay10WString = "IDELAY_10_W";
static const char *Idelay11RString = "IDELAY_11_R";
static const char *Idelay11WString = "IDELAY_11_W";
static const char *Idelay12RString = "IDELAY_12_R";
static const char *Idelay12WString = "IDELAY_12_W";
static const char *Idelay13RString = "IDELAY_13_R";
static const char *Idelay13WString = "IDELAY_13_W";
static const char *Idelay14RString = "IDELAY_14_R";
static const char *Idelay14WString = "IDELAY_14_W";
static const char *Idelay15RString = "IDELAY_15_R";
static const char *Idelay15WString = "IDELAY_15_W";
static const char *Idelay1RString = "IDELAY_1_R";
static const char *Idelay1WString = "IDELAY_1_W";
static const char *Idelay2RString = "IDELAY_2_R";
static const char *Idelay2WString = "IDELAY_2_W";
static const char *Idelay3RString = "IDELAY_3_R";
static const char *Idelay3WString = "IDELAY_3_W";
static const char *Idelay4RString = "IDELAY_4_R";
static const char *Idelay4WString = "IDELAY_4_W";
static const char *Idelay5RString = "IDELAY_5_R";
static const char *Idelay5WString = "IDELAY_5_W";
static const char *Idelay6RString = "IDELAY_6_R";
static const char *Idelay6WString = "IDELAY_6_W";
static const char *Idelay7RString = "IDELAY_7_R";
static const char *Idelay7WString = "IDELAY_7_W";
static const char *Idelay8RString = "IDELAY_8_R";
static const char *Idelay8WString = "IDELAY_8_W";
static const char *Idelay9RString = "IDELAY_9_R";
static const char *Idelay9WString = "IDELAY_9_W";
static const char *IdelayU21WString = "IDELAY_U2_1_W";
static const char *IdelayU22WString = "IDELAY_U2_2_W";
static const char *IdelayU31WString = "IDELAY_U3_1_W";
static const char *IdelayU32WString = "IDELAY_U3_2_W";
static const char *IdelayLdWString = "IDELAY_LD_W";
static const char *IdelayValueOutU2Bits19To0RString = "IDELAY_VALUE_OUT_U2BITS19TO0_R";
static const char *IdelayValueOutU2Bits39To20RString = "IDELAY_VALUE_OUT_U2BITS39TO20_R";
static const char *IdelayValueOutU3Bits19To0RString = "IDELAY_VALUE_OUT_U3BITS19TO0_R";
static const char *IdelayValueOutU3Bits39To20RString = "IDELAY_VALUE_OUT_U3BITS39TO20_R";
static const char *IdelayValueWString = "IDELAY_VALUE_W";
static const char *IdelayctrlResetRWString = "IDELAYCTRL_RESET_R_W";
static const char *LlspiResultRString = "LLSPI_RESULT_R";
static const char *LlspiStatusRString = "LLSPI_STATUS_R";
static const char *LlspiWeWString = "LLSPI_WE_W";
static const char *LoAmpRString = "LO_AMP_R";
static const char *LoAmpWString = "LO_AMP_W";
static const char *MinmaxResetWString = "MINMAX_RESET_W";
static const char *ModuloRString = "MODULO_R";
static const char *ModuloWString = "MODULO_W";
static const char *O_WoRString = "O_WO_R";
static const char *PeriphConfigRString = "PERIPH_CONFIG_R";
static const char *PeriphConfigWString = "PERIPH_CONFIG_W";
static const char *PhaseStepHRString = "PHASE_STEP_H_R";
static const char *PhaseStepHWString = "PHASE_STEP_H_W";
static const char *PhaseStepLRString = "PHASE_STEP_L_R";
static const char *PhaseStepLWString = "PHASE_STEP_L_W";
static const char *PhasexDoutRString = "PHASEX_DOUT_R";
static const char *PhasexStatusRString = "PHASEX_STATUS_R";
static const char *PhasexTrigWString = "PHASEX_TRIG_W";
static const char *RawadcRewindWString = "RAWADC_REWIND_W";
static const char *RawadcTrigWString = "RAWADC_TRIG_W";
static const char *RewindWString = "REWIND_W";
static const char *RldRString = "RLD_R";
static const char *ScanTriggerWString = "SCAN_TRIGGER_W";
static const char *ScannerDebugRString = "SCANNER_DEBUG_R";
static const char *ScannerDebugWString = "SCANNER_DEBUG_W";
static const char *ScannerResultRString = "SCANNER_RESULT_R";
static const char *SfpAddressSetWString = "SFP_ADDRESS_SET_W";
static const char *SlowChainOutRString = "SLOW_CHAIN_OUT_R";
static const char *SyncAd7794CsetRString = "SYNC_AD7794_CSET_R";
static const char *SyncAd7794CsetWString = "SYNC_AD7794_CSET_W";
static const char *SyncTps62210CsetRString = "SYNC_TPS62210_CSET_R";
static const char *SyncTps62210CsetWString = "SYNC_TPS62210_CSET_W";
static const char *TagNowWString = "TAG_NOW_W";
static const char *TraceKeepRString = "TRACE_KEEP_R";
static const char *TraceKeepWString = "TRACE_KEEP_W";
static const char *TraceStatus2RString = "TRACE_STATUS2_R";
static const char *TraceStatusRString = "TRACE_STATUS_R";
static const char *TrigInternalRString = "TRIG_INTERNAL_R";
static const char *TrigInternalWString = "TRIG_INTERNAL_W";
static const char *Wave0OutRString = "WAVE0_OUT_R";
static const char *Wave0SrcRString = "WAVE0_SRC_R";
static const char *Wave0SrcWString = "WAVE0_SRC_W";
static const char *Wave1OutRString = "WAVE1_OUT_R";
static const char *Wave1SrcRString = "WAVE1_SRC_R";
static const char *Wave1SrcWString = "WAVE1_SRC_W";
static const char *WaveformsAvailableRString = "WAVEFORMS_AVAILABLE_R";

static const char *WaveformString = "WAVEFORM";

static const unsigned int readRegCount = 94;
static const unsigned int writeRegCount = 73;


class scllrfPRC: public scllrfAsynPortDriver
{
public:
	scllrfPRC(const char *drvPortName, const char *netPortName);
	virtual ~scllrfPRC();
	asynStatus writeInt32(asynUser *pasynUser, epicsInt32 value);
	asynStatus writeInt32Array(asynUser *pasynUser, epicsInt32 *value,
			size_t nElements);
	
	/* Define a polling mechanism.
	 * Sends requests for all register data at a specified period.
	 * A separate thread processes the response.
	 */
	
	void waveformRequester(); // When signaled that waveforms are waiting, request them.

	virtual void init();

protected:

	virtual asynStatus startWaveformRequester(); // For system startup
	FpgaReg pReqIQ16bAMsg_[waveSegmentCount][waveSegmentSize]; // Canned message to request 16 bit I/Q data, first npt_ points
	FpgaReg pReqIQ16bBMsg_[waveSegmentCount][waveSegmentSize]; // Canned message to request 16 bit I/Q data, last npt_ points
	FpgaReg pReqI22bMsg_[waveSegmentCount][waveSegmentSize]; // Canned message to request 22 bit I data
	FpgaReg pReqQ22bMsg_[waveSegmentCount][waveSegmentSize]; // Canned message to request 22 bit Q data
	size_t npt_; /**< Number of points in each waveform buffer */
	unsigned int nchan_;
	void fillWavReqMsg();
	void reqOneWaveform(FpgaReg (*readWaveformsMsg)[waveSegmentSize]);
	//	std::ostringstream strGitSHA1;
	enum { read22bit, read16bit } wavBitWidth;
	epicsInt32 pWaveform_[maxWavesCount][waveBuffSize];

	virtual asynStatus processRegWriteResponse(const FpgaReg *pFromFpga);
	virtual asynStatus processRegReadback(const FpgaReg *pFromFpga,
			bool &waveIsReady); // parse register data, write to PVs
	virtual asynStatus processWaveReadback(const FpgaReg *pFromFpga); // parse register data, write to array PV
//	virtual asynStatus catGitSHA1(); // Once the individual bytes are all read into registers, concatenate them into a string
	virtual asynStatus functionToRegister(const int function, FpgaReg *pToFpga); /**< Translate asyn function number/reason to a register address */


	/** Values used for pasynUser->reason, and indexes into the parameter library.
	 * For this prototype, it's read only values that identify the FPGA. */

/* Registers */
    int p_x0D0A0D0AR;
#define FIRST_PRC_PARAM p_x0D0A0D0AR
    int p_HellR;
    int p_U15SdioAsSdoR;
    int p_U15SdoAddrR;
    int p_U15SpiAddrRR;
    int p_U15SpiAddrRW;
    int p_U15SpiDataRR;
    int p_U15SpiDataRW;
    int p_U15SpiReadRR;
    int p_U15SpiReadRW;
    int p_U15SpiReadyR;
    int p_U15SpiStartRR;
    int p_U15SpiStartRW;
    int p_U18SdioAsSdoR;
    int p_U18SdoAddrR;
    int p_U18SpiAddrRR;
    int p_U18SpiAddrRW;
    int p_U18SpiDataRR;
    int p_U18SpiDataRW;
    int p_U18SpiReadRR;
    int p_U18SpiReadRW;
    int p_U18SpiReadyR;
    int p_U18SpiStartRR;
    int p_U18SpiStartRW;
    int p_U2ClkResetRW;
    int p_U2IserdesResetRW;
    int p_U2Doutbits31To0R;
    int p_U2Doutbits63To32R;
    int p_U3ClkResetRW;
    int p_U3IserdesResetRW;
    int p_U3Doutbits31To0R;
    int p_U3Doutbits63To32R;
    int p_U15SpiRdbkR;
    int p_U18SpiRdbkR;
    int p_AdcTestModeR;
    int p_AdcTestModeW;
    int p_AdcTestResetW;
    int p_AdcTestTrigCntR;
    int p_AdcTestWave1OutR;
    int p_AdcTestWave2OutR;
    int p_AdcTestWave3OutR;
    int p_AdcTestWave4OutR;
    int p_AmplitudeR;
    int p_AmplitudeW;
    int p_AverageLenR;
    int p_AverageLenW;
    int p_BanyanBufR;
    int p_BanyanMaskR;
    int p_BanyanMaskW;
    int p_BanyanStatusR;
    int p_BitslipW;
    int p_BufTrigW;
    int p_CicPeriodR;
    int p_CicPeriodW;
    int p_CicShiftR;
    int p_CicShiftW;
    int p_ClkPhaseDiffOutU2R;
    int p_ClkPhaseDiffOutU3R;
    int p_DacDdsResetW;
    int p_DacModeR;
    int p_DacModeW;
    int p_DdsaModuloR;
    int p_DdsaModuloW;
    int p_DdsaPhstepHR;
    int p_DdsaPhstepHW;
    int p_DdsaPhstepLR;
    int p_DdsaPhstepLW;
    int p_FfffffffR;
    int p_Frequency4XoutR;
    int p_FrequencyClkout3R;
    int p_FrequencyDcoR;
    int p_FrequencyR;
    int p_HistCountW;
    int p_HistDoutR;
    int p_HistStatusR;
    int p_HwResetR;
    int p_HwResetW;
    int p_Idelay0R;
    int p_Idelay0W;
    int p_Idelay10R;
    int p_Idelay10W;
    int p_Idelay11R;
    int p_Idelay11W;
    int p_Idelay12R;
    int p_Idelay12W;
    int p_Idelay13R;
    int p_Idelay13W;
    int p_Idelay14R;
    int p_Idelay14W;
    int p_Idelay15R;
    int p_Idelay15W;
    int p_Idelay1R;
    int p_Idelay1W;
    int p_Idelay2R;
    int p_Idelay2W;
    int p_Idelay3R;
    int p_Idelay3W;
    int p_Idelay4R;
    int p_Idelay4W;
    int p_Idelay5R;
    int p_Idelay5W;
    int p_Idelay6R;
    int p_Idelay6W;
    int p_Idelay7R;
    int p_Idelay7W;
    int p_Idelay8R;
    int p_Idelay8W;
    int p_Idelay9R;
    int p_Idelay9W;
    int p_IdelayU21W;
    int p_IdelayU22W;
    int p_IdelayU31W;
    int p_IdelayU32W;
    int p_IdelayLdW;
    int p_IdelayValueOutU2Bits19To0R;
    int p_IdelayValueOutU2Bits39To20R;
    int p_IdelayValueOutU3Bits19To0R;
    int p_IdelayValueOutU3Bits39To20R;
    int p_IdelayValueW;
    int p_IdelayctrlResetRW;
    int p_LlspiResultR;
    int p_LlspiStatusR;
    int p_LlspiWeW;
    int p_LoAmpR;
    int p_LoAmpW;
    int p_MinmaxResetW;
    int p_ModuloR;
    int p_ModuloW;
    int p_O_WoR;
    int p_PeriphConfigR;
    int p_PeriphConfigW;
    int p_PhaseStepHR;
    int p_PhaseStepHW;
    int p_PhaseStepLR;
    int p_PhaseStepLW;
    int p_PhasexDoutR;
    int p_PhasexStatusR;
    int p_PhasexTrigW;
    int p_RawadcRewindW;
    int p_RawadcTrigW;
    int p_RewindW;
    int p_RldR;
    int p_ScanTriggerW;
    int p_ScannerDebugR;
    int p_ScannerDebugW;
    int p_ScannerResultR;
    int p_SfpAddressSetW;
    int p_SlowChainOutR;
    int p_SyncAd7794CsetR;
    int p_SyncAd7794CsetW;
    int p_SyncTps62210CsetR;
    int p_SyncTps62210CsetW;
    int p_TagNowW;
    int p_TraceKeepR;
    int p_TraceKeepW;
    int p_TraceStatus2R;
    int p_TraceStatusR;
    int p_TrigInternalR;
    int p_TrigInternalW;
    int p_Wave0OutR;
    int p_Wave0SrcR;
    int p_Wave0SrcW;
    int p_Wave1OutR;
    int p_Wave1SrcR;
    int p_Wave1SrcW;
    int p_Waveform;
    int p_WaveformsAvailableR;
    #define LAST_PRC_PARAM p_WaveformsAvailableR


#define NUM_PRC_PARAMS (&LAST_PRC_PARAM - &FIRST_PRC_PARAM + 1 + NUM_SCLLRF_PARAMS)

	// mapping of register names to addresses

    // mapping of register names to addresses
    enum ReadRegAddrs
    {
    	AdcMmcmRAdr = 0x00800000,
    	AdcTestModeRAdr = 0x00800016,
    	AdcTestResetRAdr = 0x00800017,
    	AdcTestTrigCntRAdr = 0x00000040,
    	AdcTestWave1OutRAdr = 0x00000016,
    	AdcTestWave2OutRAdr = 0x00000017,
    	AdcTestWave3OutRAdr = 0x00000018,
    	AdcTestWave4OutRAdr = 0x00000019,
    	AmplitudeRAdr = 0x00800018,
    	AverageLenRAdr = 0x00800019,
    	BanyanBufRAdr = 0x00120000,
    	BanyanMaskRAdr = 0x0080000A,
    	BanyanStatusRAdr = 0x00000042,
    	BitslipRAdr = 0x0080000B,
    	BufTrigRAdr = 0x0080001A,
    	CicPeriodRAdr = 0x0080001B,
    	CicShiftRAdr = 0x0080001C,
    	ClkPhaseDiffOutU2RAdr = 0x0000002F,
    	ClkPhaseDiffOutU3RAdr = 0x00000030,
    	CtraceRunningRAdr = 0x0000001C,
    	DacDdsResetRAdr = 0x0080001D,
    	DacModeRAdr = 0x0080001E,
    	DdsaModuloRAdr = 0x0080001F,
    	DdsaPhstepHRAdr = 0x00800020,
    	DdsaPhstepLRAdr = 0x00800021,
    	DigitizerSlowreadTagNowRAdr = 0x00800032,
    	FfffffffRAdr = 0x00000007,
    	Frequency4XoutRAdr = 0x00000009,
    	FrequencyAdcRAdr = 0x00000008,
    	FrequencyClkout3RAdr = 0x0000000A,
    	FrequencyDcoRAdr = 0x0000000B,
    	FrequencyRAdr = 0x00000008,
    	HellRAdr = 0x00000000,
    	HistCountWStrobeRAdr = 0x00800022,
    	HistDoutRAdr = 0x00100000,
    	HistStatusRAdr = 0x0000001F,
    	HwResetRAdr = 0x00000080,
    	Idelay0RAdr = 0x00000070,
    	Idelay10RAdr = 0x0000007A,
    	Idelay11RAdr = 0x0000007B,
    	Idelay12RAdr = 0x0000007C,
    	Idelay13RAdr = 0x0000007D,
    	Idelay14RAdr = 0x0000007E,
    	Idelay15RAdr = 0x0000007F,
    	Idelay1RAdr = 0x00000071,
    	Idelay2RAdr = 0x00000072,
    	Idelay3RAdr = 0x00000073,
    	Idelay4RAdr = 0x00000074,
    	Idelay5RAdr = 0x00000075,
    	Idelay6RAdr = 0x00000076,
    	Idelay7RAdr = 0x00000077,
    	Idelay8RAdr = 0x00000078,
    	Idelay9RAdr = 0x00000079,
    	IdelayValueOutU2Bits19To0RAdr = 0x0000000E,
    	IdelayValueOutU2Bits39To20RAdr = 0x0000000F,
    	IdelayValueOutU3Bits19To0RAdr = 0x00000012,
    	IdelayValueOutU3Bits39To20RAdr = 0x00000013,
    	IdelayctrlResetRAdr = 0x0080000C,
    	LlspiResultRAdr = 0x00000005,
    	LlspiStatusRAdr = 0x00000004,
    	LoAmpRAdr = 0x00800023,
    	MmcmResetRAdr = 0x0080000E,
    	ModuloRAdr = 0x00800024,
    	O_WoRAdr = 0x00000001,
    	PeriphConfigRAdr = 0x0080000F,
    	PhaseStepHRAdr = 0x00800025,
    	PhaseStepLRAdr = 0x00800026,
    	PhasexDoutRAdr = 0x00110000,
    	PhasexStatusRAdr = 0x0000002E,
    	PhasexTrigRAdr = 0x00800010,
    	QsfpI2CRegRAdr = 0x00800034,
    	RawadcTrigRAdr = 0x00800011,
    	RewindRAdr = 0x00800027,
    	RldRAdr = 0x00000002,
    	ScanTriggerWeRAdr = 0x00800012,
    	ScannerDebugRAdr = 0x00800013,
    	ScannerResultRAdr = 0x00130000,
    	SfpAddressSetRAdr = 0x00800035,
    	SlowChainOutRAdr = 0x00000043,
    	SyncAd7794CsetRAdr = 0x00800014,
    	SyncTps62210CsetRAdr = 0x00800015,
    	TraceKeepRAdr = 0x0080002C,
    	TraceResetWeRAdr = 0x0080002D,
    	TraceStatus2RAdr = 0x00000045,
    	TraceStatusRAdr = 0x00000044,
    	TrigInternalRAdr = 0x0080002E,
    	TrigModeRAdr = 0x0080002F,
    	U15SdioAsSdoRAdr = 0x00000039,
    	U15SdoAddrRAdr = 0x00000038,
    	U15SpiDataAddrRAdr = 0x00800001,
    	U15SpiRdbkRAdr = 0x00000038,
    	U15SpiReadRRAdr = 0x00000092,
    	U15SpiReadyRAdr = 0x00000039,
    	U15SpiStartRRAdr = 0x00000092,
		U15SpiAddrRRAdr = 0x00000093,
    	U15SpiDataRRAdr = 0x00000093,
    	U18SdioAsSdoRAdr = 0x0000003D,
    	U18SdoAddrRAdr = 0x0000003C,
    	U18SpiAddrRRAdr = 0x00000095,
    	U18SpiDataRRAdr = 0x00000095,
    	U18SpiRdbkRAdr = 0x0000003C,
    	U18SpiReadRRAdr = 0x00000094,
    	U18SpiReadyRAdr = 0x0000003D,
    	U18SpiStartRRAdr = 0x00000094,
    	U2Doutbits31To0RAdr = 0x0000000C,
    	U2Doutbits63To32RAdr = 0x0000000D,
    	U3Doutbits31To0RAdr = 0x00000010,
    	U3Doutbits63To32RAdr = 0x00000011,
    	Wave0OutRAdr = 0x00000014,
    	Wave0SrcRAdr = 0x00800030,
    	Wave1OutRAdr = 0x00000015,
    	Wave1SrcRAdr = 0x00800031,
    	WaveformsAvailableRAdr = 0x00000041,
    	x0D0A0D0ARAdr = 0x00000003,
    };

    // mapping of register names to addresses
    enum RegWriteAddrs
    {
    	AdcMmcmWAdr = 0x00800000,
    	AdcTestModeWAdr = 0x00800016,
    	AdcTestResetWAdr = 0x00800017,
    	AdcTestTrigCntWAdr = 0x00000040,
    	AdcTestWave1OutWAdr = 0x00000016,
    	AdcTestWave2OutWAdr = 0x00000017,
    	AdcTestWave3OutWAdr = 0x00000018,
    	AdcTestWave4OutWAdr = 0x00000019,
    	AmplitudeWAdr = 0x00800018,
    	AverageLenWAdr = 0x00800019,
    	BanyanBufWAdr = 0x00120000,
    	BanyanMaskWAdr = 0x0080000A,
    	BanyanStatusWAdr = 0x00000042,
    	BitslipWAdr = 0x0080000B,
    	BufTrigWAdr = 0x0080001A,
    	CicPeriodWAdr = 0x0080001B,
    	CicShiftWAdr = 0x0080001C,
    	ClkPhaseDiffOutU2WAdr = 0x0000002F,
    	ClkPhaseDiffOutU3WAdr = 0x00000030,
    	CtraceRunningWAdr = 0x0000001C,
    	DacDdsResetWAdr = 0x0080001D,
    	DacModeWAdr = 0x0080001E,
    	DdsaModuloWAdr = 0x0080001F,
    	DdsaPhstepHWAdr = 0x00800020,
    	DdsaPhstepLWAdr = 0x00800021,
    	HistCountWAdr = 0x00000024,
    	HwResetWAdr = 0x00000080,
    	Idelay0WAdr = 0x00000070,
    	Idelay10WAdr = 0x0000007A,
    	Idelay11WAdr = 0x0000007B,
    	Idelay12WAdr = 0x0000007C,
    	Idelay13WAdr = 0x0000007D,
    	Idelay14WAdr = 0x0000007E,
    	Idelay15WAdr = 0x0000007F,
    	Idelay1WAdr = 0x00000071,
    	Idelay2WAdr = 0x00000072,
    	Idelay3WAdr = 0x00000073,
    	Idelay4WAdr = 0x00000074,
    	Idelay5WAdr = 0x00000075,
    	Idelay6WAdr = 0x00000076,
    	Idelay7WAdr = 0x00000077,
    	Idelay8WAdr = 0x00000078,
    	Idelay9WAdr = 0x00000079,
    	IdelayLdWAdr = 0x0000000B,
    	IdelayU21WAdr = 0x0000000D,
    	IdelayU22WAdr = 0x0000000E,
    	IdelayU31WAdr = 0x0000000F,
    	IdelayU32WAdr = 0x00000010,
    	IdelayValueWAdr = 0x00000001,
    	IdelayctrlResetRWAdr = 0x00000025,
    	LlspiWeWAdr = 0x00000005,
    	LoAmpWAdr = 0x00000099,
    	MinmaxResetWAdr = 0x00000020,
    	ModuloWAdr = 0x0000008C,
    	PeriphConfigWAdr = 0x00000081,
    	PhaseStepHWAdr = 0x0000008A,
    	PhaseStepLWAdr = 0x0000008B,
    	PhasexTrigWAdr = 0x00000028,
    	RawadcRewindWAdr = 0x0000002A,
    	RawadcTrigWAdr = 0x00000029,
    	RewindWAdr = 0x0000001E,
    	ScanTriggerWAdr = 0x00000036,
    	ScannerDebugWAdr = 0x00000098,
    	SfpAddressSetWAdr = 0x00000038,
    	SyncAd7794CsetWAdr = 0x00000096,
    	SyncTps62210CsetWAdr = 0x00000097,
    	TagNowWAdr = 0x00000035,
    	TraceKeepWAdr = 0x0080002C,
    	TraceResetWAdr = 0x0080002D,
    	TrigInternalWAdr = 0x00000090,
    	U15SpiAddrRWAdr = 0x00000093,
    	U15SpiDataRWAdr = 0x00000093,
    	U15SpiReadRWAdr = 0x00000092,
    	U15SpiStartRWAdr = 0x00000092,
    	U18SpiAddrRWAdr = 0x00000095,
    	U18SpiDataRWAdr = 0x00000095,
    	U18SpiReadRWAdr = 0x00000094,
    	U18SpiStartRWAdr = 0x00000094,
    	U2ClkResetRWAdr = 0x00000021,
    	U2IserdesResetRWAdr = 0x00000026,
    	U3ClkResetRWAdr = 0x00000022,
    	U3IserdesResetRWAdr = 0x00000027,
    	Wave0SrcWAdr = 0x00000087,
    	Wave1SrcWAdr = 0x00000088,
    };

    // masks applied to returned register data
    enum RegMasks
    {
    	AdcMmcmMask =  0x00000003,
    	U15SpiDataAddrRMask =  0xFFFFFFFF,
    	U15SpiReadAndStartRMask =  0x00000003,
    	U18SpiDataAddrRMask =  0xFFFFFFFF,
    	U18SpiReadAndStartRMask =  0x00000003,
    	U2ClkResetRMask =  0x00000001,
    	U2IserdesResetRMask =  0x00000001,
    	U3ClkResetRMask =  0x00000001,
    	U3IserdesResetRMask =  0x00000001,
    	U4ResetRMask =  0x00000001,
    	BanyanMaskMask =  0x000000FF,
    	BitslipMask =  0x0000FFFF,
    	IdelayctrlResetRMask =  0x00000001,
    	LlspiWeMask =  0x00000001,
    	MmcmResetRMask =  0x00000001,
    	PeriphConfigMask =  0xFFFFFFFF,
    	PhasexTrigMask =  0x00000001,
    	RawadcTrigMask =  0x00000001,
    	ScanTriggerWeMask =  0x00000001,
    	ScannerDebugMask =  0x0000001F,
    	SyncAd7794CsetMask =  0x000003FF,
    	SyncTps62210CsetMask =  0x0000003F,
    	AdcTestModeMask =  0x00000007,
    	AdcTestResetMask =  0x00000001,
    	AmplitudeMask =  0x0000FFFF,
    	AverageLenMask =  0x3FFFFFFF,
    	BufTrigMask =  0x00000001,
    	CicPeriodMask =  0x00003FFF,
    	CicShiftMask =  0x0000000F,
    	DacDdsResetMask =  0x00000001,
    	DacModeMask =  0x0000000F,
    	DdsaModuloMask =  0x00000FFF,
    	DdsaPhstepHMask =  0x000FFFFF,
    	DdsaPhstepLMask =  0x00000FFF,
    	HistCountWStrobeMask =  0x00000001,
    	LoAmpMask =  0x0003FFFF,
    	ModuloMask =  0x00000FFF,
    	PhaseStepHMask =  0x000FFFFF,
    	PhaseStepLMask =  0x00000FFF,
    	RewindMask =  0x00000001,
    	SsaStimAmpstepMask =  0x0000FFFF,
    	SsaStimEnMask =  0x00000001,
    	SsaStimGPeriodMask =  0x000003FF,
    	SsaStimPertstepMask =  0x0000FFFF,
    	TraceKeepMask =  0x000000FF,
    	TraceResetWeMask =  0x00000001,
    	TrigInternalMask =  0x00000001,
    	TrigModeMask =  0x00000003,
    	Wave0SrcMask =  0x00000007,
    	Wave1SrcMask =  0x00000007,
    	DigitizerSlowreadTagNowMask =  0x000000FF,
    	IccCfgMask =  0xFFFFFFFF,
    	QsfpI2CRegMask =  0xFFFFFFFF,
    	SfpAddressSetMask =  0x0000FFFF,
    
    	TraceKeepRMask = 0x000000FF,
    	TraceKeepWMask = 0x000000FF,
		waveIsReadyMask = 0x4000000, // for trace status reg
		nptMask = 0x3F000000 // for trace status reg
    };
};

#endif /* SCLLRFAPP_SRC_SCLLRFPRC_H_ */
